name: Run tests for Anclap's anchor

on:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Run tests
      run: yarn run-tests
