name: Run tests for Anclap's anchor.

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build:all

    - name: Run tests
      run: yarn run-tests
